blank_issues_enabled: false
contact_links:
  - name: WhatsApp Channel
    url: https://whatsapp.com/channel/0029VbCyzd99Bb5sXWGwGE29
    about: Updates, announcements, and community discussion
  - name: Website
    url: https://www.senxyzmusic.biz.id
    about: Official SenxyzMusic website
